name: Publish Development Build
on:
  push:
    branches:
      - 'master'
      - '1.21.1'
      - '1.20.4'
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Read Gradle Properties
        id: gradle-properties
        run: |
            ./gradlew properties -q | grep "^minecraft_version:" | awk '{print $2}' > .minecraft_version
            echo "MINECRAFT_VERSION=$(cat .minecraft_version)" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: true
          title: Delirious for Minecraft ${{ env.MINECRAFT_VERSION }}
          files: |
            ./build/libs/*.jar
